title: "#TokenEthics"
project: "#TokenEthics Home Page"
description: "Documents & Community Discussions on #TokenEthics"
author: Christopher Allen
email: ChristopherA@LifeWithAlacrity.com
twitter_username: ChristopherA
github_username:  ChristopherA
show_downloads: false
google_analytics:
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end
