name: name
title: \#TokenEthics Home Page
project: \#TokenEthics
subtitle: subtitle
description: Documents & Community Discussions on \#TokenEthics
author: Christopher Allen
email: ChristopherA@LifeWithAlacrity.com
twitter_username: ChristopherA
github_username:  ChristopherA
theme: jekyll-theme-cayman
